### ISSUE TITLE
jest throws as beforeAll is undefined

### ISSUE THREAD

**Issue by michaeljota** [getsaf/shallow-render#113]
I don't know if it is just after Jest 24, but I'm trying to run this with a fresh angular cli project, using Jest with [@angular-builders/jest](https://www.npmjs.com/package/@angular-builders/jest) and it's throwing because `beforeAll` is undefined. 

The stracktrace for what it's worth it. 

```
    TypeError: testFramework.beforeAll is not a function

       5 | import { Shallow } from 'shallow-render';
       6 | 
    >  7 | Shallow.alwaysReplaceModule(RouterModule, RouterTestingModule);
         |                          ^
       8 | Shallow.alwaysReplaceModule(HttpClientModule, HttpClientTestingModule);
       9 | 

      at Object.<anonymous> (../../node_modules/shallow-render/dist/lib/test-framework.js:17:15)
      at Object.<anonymous> (../../node_modules/shallow-render/dist/lib/models/renderer.js:180:24)
      at Object.<anonymous> (../../node_modules/shallow-render/dist/lib/shallow.js:158:18)
      at Object.<anonymous> (../../node_modules/shallow-render/dist/index.js:7:17)
      at Object.<anonymous> (src/test.ts:7:26)
```

**Comment by michaeljota** [comment]
NVM: I was trying to use `setupFiles` to setup Shallow, but seems that it should be `setupFilesAfterEnv` instead. Thanks!
