### ISSUE TITLE
Doesn't work with jest

### ISSUE THREAD

**Issue by marcus-sa** [getsaf/shallow-render#129]
I keep hitting these errors when rendering a component
```sh
console.error ../../node_modules/jsdom/lib/jsdom/virtual-console.js:29
    Error: Error: connect ECONNREFUSED 127.0.0.1:80
        at Object.dispatchError (/home/marcus-sa/Git/siteattention/dashboard/node_modules/jsdom/lib/jsdom/living/xhr-utils.js:54:19)
        at Request.<anonymous> (/home/marcus-sa/Git/siteattention/dashboard/node_modules/jsdom/lib/jsdom/living/xmlhttprequest.js:675:20)
        at Request.emit (events.js:214:15)
        at Request.onRequestError (/home/marcus-sa/Git/siteattention/dashboard/node_modules/request/request.js:881:8)
        at ClientRequest.emit (events.js:209:13)
        at Socket.socketErrorListener (_http_client.js:406:9)
        at Socket.emit (events.js:209:13)
        at emitErrorNT (internal/streams/destroy.js:91:8)
        at emitErrorAndCloseNT (internal/streams/destroy.js:59:3)
        at processTicksAndRejections (internal/process/task_queues.js:77:11) undefined


Error: Failed: "Failed to load users.component.html"
Error: 
    at Env.it (/home/marcus-sa/Git/siteattention/dashboard/node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:91:24)
    at it (/home/marcus-sa/Git/siteattention/dashboard/node_modules/jest-jasmine2/build/jasmine/jasmineLight.js:93:21)
    at env.<computed> (/home/marcus-sa/Git/siteattention/dashboard/node_modules/jest-preset-angular/zone-patch/index.js:84:27)
    at /home/marcus-sa/Git/siteattention/dashboard/libs/users/src/lib/users.component.spec.ts:30:3
    at ZoneDelegate.invoke (/home/marcus-sa/Git/siteattention/dashboard/node_modules/zone.js/dist/zone.js:396:30)
    at Zone.run (/home/marcus-sa/Git/siteattention/dashboard/node_modules/zone.js/dist/zone.js:153:47)
    at Suite.<anonymous> (/home/marcus-sa/Git/siteattention/dashboard/node_modules/jest-preset-angular/zone-patch/index.js:40:21)
    at addSpecsToSuite (/home/marcus-sa/Git/siteattention/dashboard/node_modules/jest-jasmine2/build/jasmine/Env.js:496:51)
    at Env.describe (/home/marcus-sa/Git/siteattention/dashboard/node_modules/jest-jasmine2/build/jasmine/Env.js:466:11)
    at describe (/home/marcus-sa/Git/siteattention/dashboard/node_modules/jest-jasmine2/build/jasmine/jasmineLight.js:81:18)
```

I've seen multiple issues where people wanted Jest support and it was added.. But from what it looks like it doesn't work?
`jest-preset-angular` inlines all the HTML, so there's really no reason for it to be doing a http request to get the template.

**Comment by kreatemore** [comment]
Hey @marcus-sa, thanks for opening this issue - I'm currently using shallow-render with jest (and jest-preset-angular) in mutliple projects, so I'm sure it works, but I also know from experience, that initial jest setups can lead to some cryptic errors. I'll try to look into your logs in a bit more detail, but it'd probably help if you could post your jest config as well.

Cheers!

**Comment by marcus-sa** [comment]
Only when calling `shallow.render()` it tries to do the HTTP request.
I've tried every possible configuration, and it only fails when I use this library.

**Comment by getsaf** [comment]
Shallow render is mostly a wrapper around TestBed. The Http request is made to fetch the HTML template during the TestBed.compileComponents call. I believe it only makes an http request when the template is in a separate file than the component class. Could you try writing an equivalent test with TestBed for the same component? My guess is that the TestBed test would fail in the same manner when you called compile components.

Sorry for the lack of formatting, I'm on a phone at the moment.

**Comment by ike18t** [comment]
In the 2 diff apps that I'm using jest with angular I use this builder for
the tests:

https://www.npmjs.com/package/@angular-builders/jest

You didn't mention whether you are using this already or not but I hope
this helps.

**Comment by getsaf** [comment]
@marcus-sa Give version 8.5.0 a go, it should fix your matchers!

**Comment by marcus-sa** [comment]
@getsaf actually it was a problem with me not including html as a transform matcher for `ts-jest`
