### ISSUE TITLE
Tests fail if ng-bootstrap module is imported

### ISSUE THREAD

**Issue by thesam** [getsaf/shallow-render#62]
If NgbModule from ng-bootstrap is imported, the test fails with the following Error.

I realize that you cannot support all combinations of third-party frameworks but I'm curious if this is only a problem with ng-bootstrap or something that could be fixed in shallow-render.

Example: https://stackblitz.com/edit/shallow-render-mock-method-provider-dy21dd

```
error properties: Object({ ngSyntaxError: true })
Error: MockOfNgbModalBackdrop cannot be used as an entry component.
    at syntaxError (https://shallow-render-mock-method-provider-dy21dd.stackblitz.io/turbo_modules/@angular/compiler@6.1.1/bundles/compiler.umd.js:1093:21)
    at CompileMetadataResolver._getEntryComponentMetadata (https://shallow-render-mock-method-provider-dy21dd.stackblitz.io/turbo_modules/@angular/compiler@6.1.1/bundles/compiler.umd.js:11087:23)
    at eval (https://shallow-render-mock-method-provider-dy21dd.stackblitz.io/turbo_modules/@angular/compiler@6.1.1/bundles/compiler.umd.js:10727:57)
    at <Jasmine>
    at CompileMetadataResolver.getNgModuleMetadata (https://shallow-render-mock-method-provider-dy21dd.stackblitz.io/turbo_modules/@angular/compiler@6.1.1/bundles/compiler.umd.js:10727:22)
    at CompileMetadataResolver.getNgModuleSummary (https://shallow-render-mock-method-provider-dy21dd.stackblitz.io/turbo_modules/@angular/compiler@6.1.1/bundles/compiler.umd.js:10553:39)
    at eval (https://shallow-render-mock-method-provider-dy21dd.stackblitz.io/turbo_modules/@angular/compiler@6.1.1/bundles/compiler.umd.js:10640:59)
    at <Jasmine>
    at CompileMetadataResolver.getNgModuleMetadata (https://shallow-render-mock-method-provider-dy21dd.stackblitz.io/turbo_modules/@angular/compiler@6.1.1/bundles/compiler.umd.js:10618:53)
    at CompileMetadataResolver.getNgModuleSummary (https://shallow-render-mock-method-provider-dy21dd.stackblitz.io/turbo_modules/@angular/compiler@6.1.1/bundles/compiler.umd.js:10553:39)
```

**Comment by getsaf** [comment]
Oh man, that error message from Angular is not very helpful :-(

Thanks for the stackblitz, I get a decent amount of issues from folks working around 3rd party libraries and their internals. Without diving deep into this particular issue, *I would suggest using `neverMock` for it across the whole app*. Would be nice if Angular gave a better error message than we see in your example. Angular has not been consistent when it comes to what's 'allowed' in a module during run-time vs what's allowed during test. Seems it is more restrictive in a TestBed environment, and these issues creep in for modules that work fine in the real-world but TestBed pukes on them.

Thanks for the issue!

**Comment by getsaf** [comment]
I realize I wasn't clear in my last response. I meant to `neverMock(NgbModule)` in your global test setup. This means your tests will use the real components but that is probably not too bad since the ngb components are probably generally free of dependencies that would cause any headaches in your tests.

**Comment by thesam** [comment]
Thank you, neverMock(NgbModule) solved our problems!

**Comment by antonpegov** [comment]
@getsaf  @thesam  Oh, piple, so how to use this? Where I should put this neverMock(NgbModule)?

**Comment by shaungrady** [comment]
I'm also having the problem @antonpegov is seeing. Any thoughts @getsaf?
