### ISSUE TITLE
TypeError: this.appInits[i] is not a function 

### ISSUE THREAD

**Issue by ianmediamiser** [getsaf/shallow-render#72]
I don't know if this is something with shallow-render or something just due to our module design. But figured I'd ask and see what help you can provide.

My test file:
```
import { Shallow } from 'shallow-render'

import { DialogSortComponent } from '@agilitypr/app/briefing/composition/sortTool/sort-tool.component';
import { BriefingModule} from "@agilitypr/app/briefing/briefing.module";

describe (
    'DialogSortComponent',
    () => {
        let shallow: Shallow<DialogSortComponent>;

        beforeEach(() => {
            shallow = new Shallow(DialogSortComponent, BriefingModule)
            }
        );

        it(
            'Sort Component created',
            async () => {
                const {find} = await shallow.render('<sorttool-dialog></sorttool-dialog>');
            }
        );
    }
);
```
When I try to run the test, I an error:

```
$ yarn test --environment dev_web1mars1 --watch=false
yarn run v1.7.0
$ ng test --environment dev_web1mars1 --watch=false
 10% building modules 1/1 modules 0 active18 10 2018 10:41:36.599:INFO [karma]: Karma v3.0.0 server started at http://0.0.0.0:9876/
18 10 2018 10:41:36.602:INFO [launcher]: Launching browser ChromeHeadless with unlimited concurrency
18 10 2018 10:41:36.615:INFO [launcher]: Starting browser ChromeHeadless
18 10 2018 10:41:51.868:INFO [HeadlessChrome 0.0.0 (Ubuntu 0.0.0)]: Connected on socket JNNa6hVTyM3iXaiPAAAA with id 67817959

  DialogSortComponent
    ✗ Sort Component created
        TypeError: this.appInits[i] is not a function
            at <Jasmine>
            at ApplicationInitStatus.webpackJsonp../node_modules/@angular/core/esm5/core.js.ApplicationInitStatus.runInitializers node_modules/@angular/core/esm5/core.js:3574:34)
            at TestBed.webpackJsonp../node_modules/@angular/core/esm5/testing.js.TestBed._initIfNeeded node_modules/@angular/core/esm5/testing.js:1011:59)
            at TestBed.webpackJsonp../node_modules/@angular/core/esm5/testing.js.TestBed.createComponent node_modules/@angular/core/esm5/testing.js:1138:1)
            at Function.webpackJsonp../node_modules/@angular/core/esm5/testing.js.TestBed.createComponent node_modules/@angular/core/esm5/testing.js:837:1)
            at Renderer.<anonymous> node_modules/shallow-render/dist/lib/models/renderer.js:149:1)
            at step node_modules/shallow-render/dist/lib/models/renderer.js:50:1)
            at Object.next node_modules/shallow-render/dist/lib/models/renderer.js:31:45)
            at fulfilled node_modules/shallow-render/dist/lib/models/renderer.js:22:42)
            at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke node_modules/zone.js/dist/zone.js:388:1)
            at ProxyZoneSpec.webpackJsonp../node_modules/zone.js/dist/proxy.js.ProxyZoneSpec.onInvoke node_modules/zone.js/dist/proxy.js:128:1)

HeadlessChrome 0.0.0 (Ubuntu 0.0.0) DialogSortComponent Sort Component created FAILED
        TypeError: this.appInits[i] is not a function
            at <Jasmine>
            at ApplicationInitStatus.webpackJsonp../node_modules/@angular/core/esm5/core.js.ApplicationInitStatus.runInitializers node_modules/@angular/core/esm5/core.js:3574:34)
            at TestBed.webpackJsonp../node_modules/@angular/core/esm5/testing.js.TestBed._initIfNeeded node_modules/@angular/core/esm5/testing.js:1011:59)
            at TestBed.webpackJsonp../node_modules/@angular/core/esm5/testing.js.TestBed.createComponent node_modules/@angular/core/esm5/testing.js:1138:1)
            at Function.webpackJsonp../node_modules/@angular/core/esm5/testing.js.TestBed.createComponent node_modules/@angular/core/esm5/testing.js:837:1)
            at Renderer.<anonymous> node_modules/shallow-render/dist/lib/models/renderer.js:149:1)
            at step node_modules/shallow-render/dist/lib/models/renderer.js:50:1)
            at Object.next node_modules/shallow-render/dist/lib/models/renderer.js:31:45)
            at fulfilled node_modules/shallow-render/dist/lib/models/renderer.js:22:42)
            at ZoneDelegate.webpackJsonp../node_modules/zone.js/dist/zone.js.ZoneDelegate.invoke node_modules/zone.js/dist/zone.js:388:1)
            at ProxyZoneSpec.webpackJsonp../node_modules/zone.js/dist/proxy.js.ProxyZoneSpec.onInvoke node_modules/zone.js/dist/proxy.js:128:1)

HeadlessChrome 0.0.0 (Ubuntu 0.0.0): Executed 1 of 1 (1 FAILED) ERROR (0.889 secs / 0.807 secs)
```
I know the test doesn't do much but the line 19 causes the error (remove it and the error goes away, with it and things go bang).

A snippet for the component, to show the selector:

```
@Component({
    selector: 'sorttool-dialog',
    templateUrl: './sort-tool.component.html',
    styleUrls: [
        '../../shared/css/briefings.css',
        './sort-tool.component.css',
    ],
    providers: [
        ConfirmationService,
        StringTokenService
    ],
```
Any guidance - is this error coming from shallow-render and something that can be dealt with? Is this something due to the complexity of our module? This module is based on Angular 5.2.

**Comment by getsaf** [comment]
Thanks for posting the issue, when you say "the line 19 causes the error" I'm unsure which line you're referring to. Is this a line in a module or component?

**Comment by ianmediamiser** [comment]
Sorry - context was set in my memory. :-)
I meant line 19 in the test file 
`const {find} = await shallow.render('<sorttool-dialog></sorttool-dialog>');`
Instantiating the Shallow object works but when I try to do the shallow.render call is when an error appears.

**Comment by getsaf** [comment]
Unfortunately, I don't have enough information to figure out why your module fails when the mocked module is passed through TestBed.

My best guess is that the `BriefingModule` you are using to test is an App level module and uses an APP_INITIALIZER in it. You generally wouldn't write unit tests against something that high up. The `DialogSortComponent` would usually live in a sub-module that is imported into the `BriefingModule` like so:

```typescript
@NgModule({
  imports: [SortToolModule, FooModule, BarModule],
  providers: [{provide: APP_INITIALIZER, multi: true, useFactory: () => undefined}],
  bootstrap: [RootComponent]
})
class BriefingModule {}
```

I suspect that in your example, the `DialogSortComponent` which is located in: '@agilitypr/app/briefing/composition/sortTool/sort-tool.component' should probably be part of a `SortToolModule` and tests should be written off of that module.

I may code up something in `Shallow` to give a better error message than the one you're receiving but I don't know if it will ever support testing AppModules directly. I *may* be able to auto-skip APP_INITIALIZERS in `Shallow` but I'm unsure if it would really help this scenario.

For reference, I reproduced the error in this [StackBlitz](https://stackblitz.com/edit/github-hhokkr?file=examples/with-app-initializer.spec.ts).

I know I made a bunch of assumptions here, hopefully this helps.

**Comment by getsaf** [comment]
@ianmediamiser I just released a new version that omits all `APP_INITIALIZERS` from `Shallow` tests automatically.

Give it a whirl and see if it solves your issue. I'm not confident it will since I'm guessed at what your issue is but there's a chance it solves your problem.

**Comment by ianmediamiser** [comment]
I'll set things up to give it try early next week. Appreciate your efforts on my behalf.
